#!/usr/bin/env python3
"""Generate compact XLang3 Unicode tables from the running CPython database."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys
import unicodedata as ud
import urllib.request


MAX_UNICODE = 0x10FFFF
ALGORITHMIC_HEX_NAMES = {
    "CJK UNIFIED IDEOGRAPH",
    "CJK COMPATIBILITY IDEOGRAPH",
    "EGYPTIAN HIEROGLYPH",
    "KHITAN SMALL SCRIPT CHARACTER",
    "NUSHU CHARACTER",
}


def cpp_bytes(data: bytes, width: int = 96) -> str:
    chunks = []
    for start in range(0, len(data), width):
        part = data[start : start + width]
        chunks.append('"' + ''.join(f"\\x{byte:02x}" for byte in part) + '"')
    return "\n".join(chunks) if chunks else '""'


def append_blob(blob: bytearray, value: str) -> tuple[int, int]:
    encoded = value.encode("utf-8")
    offset = len(blob)
    blob.extend(encoded)
    return offset, len(encoded)


def parse_ucd_file(url: str) -> list[str]:
    with urllib.request.urlopen(url, timeout=30) as response:
        return response.read().decode("utf-8").splitlines()


def derived_property(lines: list[str], wanted: str) -> set[int]:
    result: set[int] = set()
    for line in lines:
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        code_range, name = [part.strip() for part in line.split(";", 1)]
        if name != wanted:
            continue
        bounds = code_range.split("..")
        start = int(bounds[0], 16)
        end = int(bounds[-1], 16)
        result.update(range(start, end + 1))
    return result


def generate_legacy(output: Path) -> None:
    """Generate the database exposed by CPython's unicodedata.ucd_3_2_0."""
    database = ud.ucd_3_2_0
    categories: list[str] = []
    bidis: list[str] = []
    widths: list[str] = []
    ranges = []
    numeric = []
    decompositions = []
    compositions = []
    names = []
    algorithmic_points: dict[str, list[int]] = {name: [] for name in ALGORITHMIC_HEX_NAMES}
    blob = bytearray()

    def index(values: list[str], value: str) -> int:
        if value not in values:
            values.append(value)
        return values.index(value)

    previous = None
    range_start = 0
    for cp in range(MAX_UNICODE + 1):
        char = chr(cp)
        props = (
            index(categories, database.category(char)),
            index(bidis, database.bidirectional(char)),
            index(widths, database.east_asian_width(char)),
            database.combining(char), database.mirrored(char),
            database.decimal(char, -1), database.digit(char, -1), 0,
        )
        if previous is None:
            previous = props
        elif props != previous:
            ranges.append((range_start, cp - 1, *previous))
            range_start = cp
            previous = props
        number = database.numeric(char, None)
        if number is not None:
            numeric.append((cp, repr(number)))
        decomposition = database.decomposition(char)
        if decomposition:
            offset, length = append_blob(blob, decomposition)
            decompositions.append((cp, offset, length))
            pieces = decomposition.split()
            if len(pieces) == 2 and not pieces[0].startswith("<"):
                first, second = (int(piece, 16) for piece in pieces)
                if database.normalize("NFC", chr(first) + chr(second)) == char:
                    compositions.append((first, second, cp))
        name = database.name(char, None)
        if name:
            match = re.fullmatch(r"(.+)-([0-9A-F]{4,6})", name)
            if match and match.group(1) in ALGORITHMIC_HEX_NAMES and int(match.group(2), 16) == cp:
                algorithmic_points[match.group(1)].append(cp)
            elif not (0xAC00 <= cp <= 0xD7A3):
                offset, length = append_blob(blob, name)
                names.append((cp, offset, length))
    ranges.append((range_start, MAX_UNICODE, *previous))
    compositions.sort()

    algorithmic_ranges = []
    for prefix in sorted(algorithmic_points):
        points = algorithmic_points[prefix]
        if not points:
            continue
        start = previous_cp = points[0]
        for cp in points[1:]:
            if cp != previous_cp + 1:
                algorithmic_ranges.append((start, previous_cp, prefix))
                start = cp
            previous_cp = cp
        algorithmic_ranges.append((start, previous_cp, prefix))

    out = [
        "// Generated by agent/scripts/generate_unicode_data.py using CPython " + sys.version.split()[0],
        "// Legacy Unicode database version 3.2.0",
        "namespace unicode_legacy_generated {",
        'constexpr char kVersion[] = "3.2.0";',
    ]
    for name, values in (("Categories", categories), ("Bidirectional", bidis), ("EastAsianWidth", widths)):
        out.append(f"constexpr const char* k{name}[] = {{" + ",".join(json.dumps(v) for v in values) + "};")
    out.append("constexpr PropertyRange kPropertyRanges[] = {")
    out.extend("{%#x,%#x,%d,%d,%d,%d,%d,%d,%d,%d}," % row for row in ranges)
    out.append("};\nconstexpr NumericRecord kNumericRecords[] = {")
    out.extend(f"{{0x{cp:x},{value}}}," for cp, value in numeric)
    out.append("};\nconstexpr BlobRecord kDecompositionRecords[] = {")
    out.extend(f"{{0x{cp:x},{offset},{length}}}," for cp, offset, length in decompositions)
    out.append("};\nconstexpr CompositionRecord kCompositionRecords[] = {")
    out.extend(f"{{0x{first:x},0x{second:x},0x{composed:x}}}," for first, second, composed in compositions)
    out.append("};\nconstexpr NameRecord kNameRecords[] = {")
    out.extend(f"{{0x{cp:x},{offset},{length}}}," for cp, offset, length in names)
    out.append("};\nconstexpr AlgorithmicRange kAlgorithmicRanges[] = {")
    for start, end, prefix in algorithmic_ranges:
        offset, length = append_blob(blob, prefix)
        out.append(f"{{0x{start:x},0x{end:x},{offset},{length}}},")
    out.append("};\nconstexpr unsigned char kBlob[] = {")
    for start in range(0, len(blob), 24):
        out.append(",".join(f"0x{value:02x}" for value in blob[start:start + 24]) + ",")
    out.append("};\n}  // namespace unicode_legacy_generated\n")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {output}: {len(ranges)} ranges, {len(names)} names, {len(blob)} blob bytes")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument("--legacy-output", type=Path)
    args = parser.parse_args()

    base = f"https://www.unicode.org/Public/{ud.unidata_version}/ucd"
    derived = parse_ucd_file(base + "/DerivedCoreProperties.txt")
    cased = derived_property(derived, "Cased")
    case_ignorable = derived_property(derived, "Case_Ignorable")

    categories: list[str] = []
    bidis: list[str] = []
    widths: list[str] = []
    ranges = []
    numeric = []
    decompositions = []
    compositions = []
    cases = []
    names = []
    algorithmic_points: dict[str, list[int]] = {name: [] for name in ALGORITHMIC_HEX_NAMES}
    blob = bytearray()

    def index(values: list[str], value: str) -> int:
        if value not in values:
            values.append(value)
        return values.index(value)

    previous = None
    range_start = 0
    for cp in range(MAX_UNICODE + 1):
        char = chr(cp)
        flags = 0
        predicates = (
            char.islower(), char.isupper(), char.istitle(), char.isalpha(),
            char.isdigit(), char.isdecimal(), char.isnumeric(), char.isalnum(),
            char.isspace(), char.isprintable(), char.isidentifier(),
            ("A" + char).isidentifier(),
        )
        for bit, enabled in enumerate(predicates):
            if enabled:
                flags |= 1 << bit
        if cp in cased:
            flags |= 1 << 12
        if cp in case_ignorable:
            flags |= 1 << 13
        props = (
            index(categories, ud.category(char)),
            index(bidis, ud.bidirectional(char)),
            index(widths, ud.east_asian_width(char)),
            ud.combining(char), ud.mirrored(char), ud.decimal(char, -1),
            ud.digit(char, -1), flags,
        )
        if previous is None:
            previous = props
        elif props != previous:
            ranges.append((range_start, cp - 1, *previous))
            range_start = cp
            previous = props

        number = ud.numeric(char, None)
        if number is not None:
            numeric.append((cp, repr(number)))
        decomposition = ud.decomposition(char)
        if decomposition:
            offset, length = append_blob(blob, decomposition)
            decompositions.append((cp, offset, length))
            pieces = decomposition.split()
            if len(pieces) == 2 and not pieces[0].startswith("<"):
                first, second = (int(piece, 16) for piece in pieces)
                if ud.normalize("NFC", chr(first) + chr(second)) == char:
                    compositions.append((first, second, cp))
        mappings = [char.lower(), char.upper(), char.title(), char.casefold()]
        if any(mapped != char for mapped in mappings):
            fields = []
            for mapped in mappings:
                fields.extend(append_blob(blob, mapped) if mapped != char else (0, 0))
            cases.append((cp, *fields))
        name = ud.name(char, None)
        if name:
            match = re.fullmatch(r"(.+)-([0-9A-F]{4,6})", name)
            if match and match.group(1) in ALGORITHMIC_HEX_NAMES and int(match.group(2), 16) == cp:
                algorithmic_points[match.group(1)].append(cp)
            elif not (0xAC00 <= cp <= 0xD7A3):
                offset, length = append_blob(blob, name)
                names.append((cp, offset, length))
    ranges.append((range_start, MAX_UNICODE, *previous))

    lookup = [(blob[offset : offset + length].decode("utf-8"), cp, offset, length)
              for cp, offset, length in names]
    for line in parse_ucd_file(base + "/NameAliases.txt"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        code, name, _kind = [part.strip() for part in line.split(";")]
        offset, length = append_blob(blob, chr(int(code, 16)))
        lookup.append((name, -1, offset, length))
    for line in parse_ucd_file(base + "/NamedSequences.txt"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        name, sequence = [part.strip() for part in line.split(";")]
        value = "".join(chr(int(code, 16)) for code in sequence.split())
        offset, length = append_blob(blob, value)
        lookup.append((name, -1, offset, length))
    lookup.sort(key=lambda item: item[0])
    compositions.sort()

    algorithmic_ranges = []
    for prefix in sorted(algorithmic_points):
        points = algorithmic_points[prefix]
        if not points:
            continue
        start = previous_cp = points[0]
        for cp in points[1:]:
            if cp != previous_cp + 1:
                algorithmic_ranges.append((start, previous_cp, prefix))
                start = cp
            previous_cp = cp
        algorithmic_ranges.append((start, previous_cp, prefix))

    out = []
    out.append("// Generated by agent/scripts/generate_unicode_data.py using CPython " + sys.version.split()[0])
    out.append("// Unicode database version " + ud.unidata_version)
    out.append("namespace unicode_generated {")
    out.append(f'constexpr char kVersion[] = "{ud.unidata_version}";')
    for name, values in (("Categories", categories), ("Bidirectional", bidis), ("EastAsianWidth", widths)):
        out.append(f"constexpr const char* k{name}[] = {{" + ",".join(json.dumps(v) for v in values) + "};")
    out.append("constexpr PropertyRange kPropertyRanges[] = {")
    out.extend("{%#x,%#x,%d,%d,%d,%d,%d,%d,%d,%d}," % row for row in ranges)
    out.append("};")
    out.append("constexpr NumericRecord kNumericRecords[] = {")
    out.extend(f"{{0x{cp:x},{value}}}," for cp, value in numeric)
    out.append("};")
    out.append("constexpr BlobRecord kDecompositionRecords[] = {")
    out.extend(f"{{0x{cp:x},{offset},{length}}}," for cp, offset, length in decompositions)
    out.append("};")
    out.append("constexpr CompositionRecord kCompositionRecords[] = {")
    out.extend(f"{{0x{first:x},0x{second:x},0x{composed:x}}}," for first, second, composed in compositions)
    out.append("};")
    out.append("constexpr CaseRecord kCaseRecords[] = {")
    out.extend("{" + ",".join(str(value) if i else f"0x{value:x}" for i, value in enumerate(row)) + "}," for row in cases)
    out.append("};")
    out.append("constexpr NameRecord kNameRecords[] = {")
    out.extend(f"{{0x{cp:x},{offset},{length}}}," for cp, offset, length in names)
    out.append("};")
    name_index = {cp: i for i, (cp, _offset, _length) in enumerate(names)}
    out.append("constexpr LookupRecord kLookupRecords[] = {")
    for name, cp, offset, length in lookup:
        name_offset, name_length = append_blob(blob, name)
        direct_index = name_index.get(cp, -1)
        out.append(f"{{{name_offset},{name_length},{direct_index},{offset},{length}}},")
    out.append("};")
    out.append("constexpr AlgorithmicRange kAlgorithmicRanges[] = {")
    for start, end, prefix in algorithmic_ranges:
        offset, length = append_blob(blob, prefix)
        out.append(f"{{0x{start:x},0x{end:x},{offset},{length}}},")
    out.append("};")
    out.append(f"constexpr unsigned char kBlob[] = {{")
    for start in range(0, len(blob), 24):
        out.append(",".join(f"0x{value:02x}" for value in blob[start:start+24]) + ",")
    out.append("};")
    out.append("}  // namespace unicode_generated\n")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {args.output}: {len(ranges)} ranges, {len(names)} names, {len(blob)} blob bytes")
    if args.legacy_output is not None:
        generate_legacy(args.legacy_output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
