/*
Copyright (C) 2026 CantorAI Inc. and The XLang Foundation
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
One row per converted IR opcode. This file is included inside switch(in.op).
*/

XLANG3_VM_FLOW(LoadConst, xlang3::xlang_vm::ops::load_const(in, fn, regs, result, raise_runtime_error))
XLANG3_VM_FAST(Move, xlang3::xlang_vm::ops::move(in, regs))
XLANG3_VM_FLOW(LoadLocal, xlang3::xlang_vm::ops::load_local(in, regs, locals, result, raise_runtime_error))
XLANG3_VM_FAST(StoreLocal, xlang3::xlang_vm::ops::store_local(in, regs, locals, frame.register_last_use, ip))
XLANG3_VM_FAST(MoveLocal, xlang3::xlang_vm::ops::move_local(in, locals))
XLANG3_VM_FLOW(AddLocalConst, xlang3::xlang_vm::ops::add_local_const(in, fn, locals, result, raise_runtime_error))
XLANG3_VM_FLOW(AddLocalLocal, xlang3::xlang_vm::ops::add_local_local(in, locals, result, raise_runtime_error))
XLANG3_VM_FLOW(LoadCell, xlang3::xlang_vm::ops::load_cell(in, regs, cells, result, raise_runtime_error))
XLANG3_VM_FLOW(StoreCell, xlang3::xlang_vm::ops::store_cell(in, fn, regs, locals, cells, result, raise_runtime_error))
XLANG3_VM_FAST(LoadCellObject, xlang3::xlang_vm::ops::load_cell_object(in, regs, cells))
XLANG3_VM_FLOW(LoadFree, xlang3::xlang_vm::ops::load_free(in, fn, regs, fn_obj_closure, result, raise_runtime_error))
XLANG3_VM_FLOW(StoreFree, xlang3::xlang_vm::ops::store_free(in, regs, fn_obj_closure, result, raise_runtime_error))
XLANG3_VM_FAST(LoadFreeObject, xlang3::xlang_vm::ops::load_free_object(in, regs, fn_obj_closure))
XLANG3_VM_FLOW(LoadModuleSlot, xlang3::xlang_vm::ops::load_module_slot(in, module, runtime_, regs, globals_module, globals_, result, raise_runtime_error))
XLANG3_VM_FLOW(StoreModuleSlot, xlang3::xlang_vm::ops::store_module_slot(in, module, regs, globals_module, globals_, globals_version_, result))
XLANG3_VM_FLOW(LoadGlobal, xlang3::xlang_vm::ops::load_global(in, fn, runtime_, regs, globals_module, globals_, globals_version_, instr_cache[ip], result, raise_runtime_error))
XLANG3_VM_FLOW(StoreGlobal, xlang3::xlang_vm::ops::store_global(in, fn, regs, globals_module, globals_, globals_version_, instr_cache[ip], result))
XLANG3_VM_FAST(DeleteLocal, xlang3::xlang_vm::ops::delete_local(in, locals))
XLANG3_VM_FAST(DeleteGlobal, xlang3::xlang_vm::ops::delete_global(in, fn, globals_, globals_version_))
XLANG3_VM_FLOW(DeleteModuleSlot, xlang3::xlang_vm::ops::delete_module_slot(in, module, globals_module, result, raise_runtime_error))
XLANG3_VM_FLOW(LoadAttr, xlang3::xlang_vm::ops::load_attr(in, fn, module, module_owner, runtime_, regs, instr_cache, native_call_args, ip, result, execution_lock, make_generator_if_needed, push_frame, raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(StoreAttr, xlang3::xlang_vm::ops::store_attr(in, fn, module, module_owner, runtime_, regs, instr_cache, native_call_args, ip, result, execution_lock, make_generator_if_needed, push_frame, raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(DeleteAttr, xlang3::xlang_vm::ops::delete_attr(in, fn, module, module_owner, runtime_, regs, instr_cache, native_call_args, ip, result, execution_lock, make_generator_if_needed, push_frame, raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(LoadInstanceSlot, xlang3::xlang_vm::ops::load_instance_slot(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(StoreInstanceSlot, xlang3::xlang_vm::ops::store_instance_slot(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(Call, xlang3::xlang_vm::ops::call(in, fn, module, module_owner, runtime_, regs, instr_cache, native_call_args, ip, result, execution_lock, make_generator_if_needed, push_frame, call_builtin_type_constructor, analyze_arg_binary_function, execute_arg_binary_function, analyze_slot_constructor, execute_slot_constructor, raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(CallEx, xlang3::xlang_vm::ops::call_ex(in, fn, module, module_owner, runtime_, regs, frames, frame_count, instr_cache, native_call_args, ip, result, execution_lock, make_generator_if_needed, push_frame, call_builtin_type_constructor, raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(CallMethod, xlang3::xlang_vm::ops::call_method(in, fn, module, module_owner, runtime_, regs, instr_cache, native_call_args, ip, result, execution_lock, make_generator_if_needed, push_frame, analyze_const_method, analyze_self_binary_method, execute_self_binary_method, analyze_self_slot_method, execute_self_slot_method, analyze_self_slot_const_sum_method, execute_self_slot_const_sum_method, raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(CallModuleMethod, xlang3::xlang_vm::ops::call_module_method(in, fn, module, module_owner, runtime_, regs, globals_module, instr_cache, native_call_args, ip, result, execution_lock, make_generator_if_needed, push_frame, raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(ImportModule, xlang3::xlang_vm::ops::import_module(in, fn, runtime_, regs, result, raise_import_error))
XLANG3_VM_FLOW(ImportFrom, xlang3::xlang_vm::ops::import_from(in, fn, runtime_, regs, globals_module, result, raise_import_error))
XLANG3_VM_FLOW(ImportStar, xlang3::xlang_vm::ops::import_star(in, fn, runtime_, globals_module, result, raise_import_error))
XLANG3_VM_FLOW(RawBlock, xlang3::xlang_vm::ops::raw_block(in, fn, runtime_, locals, fn_obj_closure, globals_module, globals_, globals_version_, result, raise_runtime_error))
XLANG3_VM_FLOW(MakeClass, xlang3::xlang_vm::ops::make_class(in, fn, runtime_, regs, result))
XLANG3_VM_FLOW(MakeFunction, xlang3::xlang_vm::ops::make_function(in, fn, regs, globals_module, module_owner, result))
XLANG3_VM_FLOW(SetFunctionAnnotations, xlang3::xlang_vm::ops::set_function_annotations(in, fn, regs, result))
XLANG3_VM_FLOW(SetFunctionKwDefaults, xlang3::xlang_vm::ops::set_function_kwdefaults(in, fn, regs, result))
XLANG3_VM_FLOW(SetClassBase, xlang3::xlang_vm::ops::set_class_base(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(MakeTuple, xlang3::xlang_vm::ops::make_tuple(in, fn, regs, result))
XLANG3_VM_FLOW(MakeList, xlang3::xlang_vm::ops::make_list(in, fn, regs, result))
XLANG3_VM_FLOW(MakeDict, xlang3::xlang_vm::ops::make_dict(in, fn, regs, result, runtime_, raise_exception_value))
XLANG3_VM_FLOW(MakeSet, xlang3::xlang_vm::ops::make_set(in, fn, regs, result, runtime_, raise_exception_value))
XLANG3_VM_FLOW(MakeSlice, xlang3::xlang_vm::ops::make_slice(in, regs, result))
XLANG3_VM_FLOW(ListAppend, xlang3::xlang_vm::ops::list_append(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(ListExtend, xlang3::xlang_vm::ops::list_extend(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(DictSet, xlang3::xlang_vm::ops::dict_set(in, regs, runtime_, raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(SetAdd, xlang3::xlang_vm::ops::set_add_op(in, regs, runtime_, raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(SetUpdate, xlang3::xlang_vm::ops::set_update(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(TupleFromList, xlang3::xlang_vm::ops::tuple_from_list(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(Len, xlang3::xlang_vm::ops::len(in, runtime_, regs, instr_cache[ip], raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(GetItem, xlang3::xlang_vm::ops::get_item(in, runtime_, regs, instr_cache[ip], raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(SetItem, xlang3::xlang_vm::ops::set_item(in, runtime_, regs, raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(DeleteItem, xlang3::xlang_vm::ops::delete_item(in, runtime_, regs, raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(UnpackSequence, xlang3::xlang_vm::ops::unpack_sequence(in, regs, result, raise_runtime_error))
XLANG3_VM_FLOW(GetIter, xlang3::xlang_vm::ops::get_iter(in, runtime_, regs, raise_runtime_error))
XLANG3_VM_FLOW(IterNext, xlang3::xlang_vm::ops::iter_next(in, regs, ip, raise_runtime_error))
XLANG3_VM_FLOW(ForRangeConstLocalNext, xlang3::xlang_vm::ops::for_range_const_local_next(in, fn, locals, ip, result))
XLANG3_VM_FLOW(Add, xlang3::xlang_vm::ops::add(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(Sub, xlang3::xlang_vm::ops::sub(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(Mul, xlang3::xlang_vm::ops::mul(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(Div, xlang3::xlang_vm::ops::div(in, runtime_, regs, native_call_args, execution_lock, raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(FloorDiv, xlang3::xlang_vm::ops::floor_div(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(Mod, xlang3::xlang_vm::ops::mod(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(ModConst, xlang3::xlang_vm::ops::mod_const(in, fn, regs, result, raise_runtime_error))
XLANG3_VM_FLOW(Pow, xlang3::xlang_vm::ops::pow(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(BitAnd, xlang3::xlang_vm::ops::bit_and(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(BitOr, xlang3::xlang_vm::ops::bit_or(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(BitXor, xlang3::xlang_vm::ops::bit_xor(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(Shl, xlang3::xlang_vm::ops::shl(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(Shr, xlang3::xlang_vm::ops::shr(in, regs, raise_runtime_error))
XLANG3_VM_FAST(BoolAnd, xlang3::xlang_vm::ops::bool_and(in, regs))
XLANG3_VM_FAST(BoolOr, xlang3::xlang_vm::ops::bool_or(in, regs))
XLANG3_VM_FLOW(Compare, xlang3::xlang_vm::ops::compare(in, runtime_, regs, raise_runtime_error, raise_exception_value))
XLANG3_VM_FAST(Is, xlang3::xlang_vm::ops::is_op(in, regs))
XLANG3_VM_FLOW(Contains, xlang3::xlang_vm::ops::contains_dynamic(in, module, module_owner, runtime_, regs, native_call_args, ip, result, execution_lock, make_generator_if_needed, push_frame, raise_runtime_error, raise_exception_value))
XLANG3_VM_FAST(Not, xlang3::xlang_vm::ops::not_op(in, module, regs))
XLANG3_VM_FLOW(Neg, xlang3::xlang_vm::ops::neg(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(Invert, xlang3::xlang_vm::ops::invert(in, regs, raise_runtime_error))
XLANG3_VM_FLOW(Jump, xlang3::xlang_vm::ops::jump(in, ip))
XLANG3_VM_FLOW(JumpIfFalse, xlang3::xlang_vm::ops::jump_if_false(in, module, regs, ip))
XLANG3_VM_FLOW(JumpIfLocalConstFalse, xlang3::xlang_vm::ops::jump_if_local_const_false(in, fn, locals, ip, result, raise_runtime_error))
XLANG3_VM_FAST(SetupExcept, xlang3::xlang_vm::ops::setup_except(in, exception_handlers))
XLANG3_VM_FAST(SetupWith, xlang3::xlang_vm::ops::setup_with(in, exception_handlers))
XLANG3_VM_FLOW(PopExcept, xlang3::xlang_vm::ops::pop_except(exception_handlers, result))
XLANG3_VM_FLOW(Raise, xlang3::xlang_vm::ops::raise_op(in, regs, pending_exception_cause, pending_exception_explicit_cause, current_exception, result, raise_exception_value, normalize_exception))
XLANG3_VM_FLOW(SetExceptionCause, xlang3::xlang_vm::ops::set_exception_cause(in, regs, pending_exception_cause, pending_exception_explicit_cause, result, normalize_exception))
XLANG3_VM_FLOW(Reraise, xlang3::xlang_vm::ops::reraise(current_exception, raise_exception_value, raise_runtime_error))
XLANG3_VM_FAST(ClearException, xlang3::xlang_vm::ops::clear_exception(runtime_, current_exception))
XLANG3_VM_FAST(LoadException, xlang3::xlang_vm::ops::load_exception(in, regs, current_exception))
XLANG3_VM_FAST(LoadExceptionType, xlang3::xlang_vm::ops::load_exception_type(in, runtime_, regs, current_exception))
XLANG3_VM_FAST(MatchException, xlang3::xlang_vm::ops::match_exception(in, regs, exception_matches))
XLANG3_VM_FLOW(Yield, xlang3::xlang_vm::ops::yield_op(in, regs, ip, frames, frame_count, generator, result, raise_runtime_error))
XLANG3_VM_FLOW(Return, xlang3::xlang_vm::ops::return_op(in, regs, generator, result, finish_frame))
XLANG3_VM_FLOW(Await, xlang3::xlang_vm::ops::await_op(in, runtime_, regs, raise_runtime_error, raise_exception_value))
XLANG3_VM_FLOW(YieldFrom, xlang3::xlang_vm::ops::yield_from(raise_runtime_error))
XLANG3_VM_FAST(Pop, xlang3::xlang_vm::ops::pop())
