#include "xlang3/builtins.h"
#include "xlang3/module_object.h"
namespace xlang3 { namespace { bool enabled = false;
bool set_enabled(Runtime&, const Value*, uint32_t argc, Value& out, std::string& error, void*) { if (argc > 2) { error = "faulthandler.enable() expected at most 2 arguments"; return false; } enabled = true; value_set_none(out); return true; }
bool set_enabled_kw(Runtime&, const Value* args, uint32_t argc, const NativeKeywordArg* kwargs, uint32_t kwargc, Value& out, std::string& error, void*) { if (argc > 2) { error = "faulthandler.enable() expected at most 2 arguments"; return false; } for (uint32_t i = 0; i < kwargc; ++i) { const std::string name(kwargs[i].name); if (name != "file" && name != "all_threads") { error = "faulthandler.enable() got an unexpected keyword argument '" + name + "'"; return false; } } enabled = true; value_set_none(out); return true; }
bool clear_enabled(Runtime&, const Value*, uint32_t argc, Value& out, std::string& error, void*) { if (argc) { error = "faulthandler.disable() expected no arguments"; return false; } enabled = false; value_set_none(out); return true; }
bool get_enabled(Runtime&, const Value*, uint32_t argc, Value& out, std::string& error, void*) { if (argc) { error = "faulthandler.is_enabled() expected no arguments"; return false; } value_set_bool(out, enabled); return true; }
bool cancel(Runtime&, const Value*, uint32_t argc, Value& out, std::string& error, void*) { if (argc) { error = "faulthandler.cancel_dump_traceback_later() expected no arguments"; return false; } value_set_none(out); return true; }
} void register_faulthandler_module(Runtime& runtime) { NativeModuleBuilder b(runtime, "faulthandler"); b.value("enable", runtime.make_native_function("faulthandler.enable", set_enabled, nullptr, nullptr, nullptr, false, set_enabled_kw)).function("disable", clear_enabled).function("is_enabled", get_enabled).function("cancel_dump_traceback_later", cancel); runtime.register_module("faulthandler", b.finish()); } }
